name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2

  setup-package-manager:
    needs: checkout
    runs-on: ubuntu-latest
    name: "Setup package manager"
    steps:
      - name: Get pnpm
        shell: bash
        run: npm i pnpm
      - name: Install Dependencies
        shell: bash
        run: pnpm install

  build:
    needs: setup-package-manager
    runs-on: ubuntu-latest

    steps:
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: npm i pnpm

      - uses: actions/checkout@v4
      - name: build-package
        run: pnpm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: publish
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run publish
          version: pnpm run v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
